version: '3.8'

services:
  backend:
    hostname: backend
    restart: unless-stopped
    ports:
      - 9229:9229 # For debugging
    volumes:
      - ${MEDIA_VOL}:/srv/media
      # Mount source code to restart without rebuilding image
      # (only for development)
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./backend
    environment:
      - NODE_ENV=$NODE_ENV
      - DEBUG=$BACKEND_DEBUG
    command: [npm, run, $BACKEND_START_SCRIPT]

  frontend:
    depends_on:
      - backend
    hostname: frontend
    restart: unless-stopped
    volumes:
      # Mount source code to restart without rebuilding image
      # (only for development)
      - ./frontend/src:/usr/src/app/src
    build:
      context: ./frontend

  reverse-proxy:
    depends_on:
      - backend
      - frontend
    hostname: reverse-proxy
    restart: unless-stopped
    ports:
      - 8080:80
    build:
      context: ./reverse-proxy
