version: '3.8'

volumes:
  media:

services:
  admin:
    hostname: admin
    image: docker.io/filegator/filegator:latest
    restart: unless-stopped
    user: root
    environment:
      - BASE_URL='/admin'
      - APP_PUBLIC_PATH='/admin/'
    volumes:
      - media:/var/www/filegator/repository
      - /var/www/filegator/private
      - ./configuration.php:/var/www/filegator/configuration.php
      - ./filegator-entrypoint.sh:/var/www/filegator/entrypoint.sh
    cmd: /var/www/filegator/entrypoint.sh
  backend:
    hostname: backend
    restart: unless-stopped
    ports:
      - 9229:9229 # For debugging
    volumes:
      # Mount as read only for security
      - media:/srv/media:ro
      # Mount source code to restart without rebuilding image
      # (TODO only for development)
      #- ./backend:/usr/src/app
      #- /usr/src/app/node_modules
    build:
      context: ./backend
    environment:
      - NODE_ENV=$NODE_ENV
      - DEBUG=$BACKEND_DEBUG
    command: [ npm, run, $BACKEND_START_SCRIPT ]

  frontend:
    depends_on:
      - backend
    hostname: frontend
    restart: unless-stopped
      # Mount source code to restart without rebuilding image
      # (TODO only for development)
      #- ./frontend:/usr/src/app
    build:
      context: ./frontend

  reverse-proxy:
    depends_on:
      - backend
      - frontend
      - admin
      # - swagger-ui
    hostname: reverse-proxy
    restart: unless-stopped
    ports:
      - 8005:80
    build:
      context: ./reverse-proxy

  # Interactive API documentation
  # (TODO only for development)
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   hostname: swagger-ui
  #   volumes:
  #     - ./docs:/usr/share/nginx/html/docs
  #   environment:
  #     API_URL: docs/openapi.yaml
