version: '3.8'

services:
  api-server:
    hostname: express-api
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - 3000:80
      - 9229:9229 # For debugging
    volumes:
      - ./api-server:/usr/src/app
      - /usr/src/app/node_modules
      - ${MEDIA_VOL}:/srv/media
    build:
      context: ./api-server
    environment:
      - NODE_ENV=$NODE_ENV
      - DEBUG=$DEBUG
    command: [npm, run, $API_START_SCRIPT]

  # TODO
  # frontend:
  #   depends_on:
  #     - api-server
