openapi: '3.0.2'
info:
  title: StoKa-TV API
  version: '1.0'
servers:
  - url: https://localhost:3000/
paths:
  /arrangements:
    get:
      tags: ['Arrangements']
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                example: ["1_main-arrangement", "2_secondary-arrangement"]
                items:
                  type: string
  /arrangements/{arrangement}:
    get:
      tags: ['Arrangements']
      parameters:
        - name: "arrangement"
          in: "path"
          required: true
          example: 1_main-arrangement
          schema:
            type: string
      responses:
        '404':
          description: Not found
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: 1_main-arrangement
                  metadata:
                    type: object
                    properties:
                      defined: 
                        type: boolean
                      invalid:
                        type: boolean
                        default: false
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          example: myVideo.mp4
                        type:
                          type: string
                          enum: ['image', 'video']
                          example: video
                        duration:
                          type: number
                          example: 23.57
  /arrangements/{arrangement}/{file}:
    get:
      tags: ['Arrangements']
      parameters:
        - name: "arrangement"
          in: "path"
          required: true
          example: 1_main-arrangement
          schema:
            type: string
        - name: "file"
          in: "path"
          required: true
          example: myVideo.mp4
          schema:
            type: string
      responses:
        '404':
          description: Not found
        '200':
          description: OK
          content:
            'video/mp4':
              schema:
                type: string
                format: binary
            'image/jpeg':
              schema:
                type: string
                format: binary
            'image/png':
              schema:
                type: string
                format: binary
