openapi: 3.0.2
info:
  title: StoKa-TV API
  version: '1.0'
servers:
  - url: 'http://localhost:8080{apiBasePath}'
    variables:
      apiBasePath:
        default: /api
paths:
  /arrangements:
    get:
      tags:
        - Arrangements
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                example:
                  - 1_main-arrangement
                  - 2_secondary-arrangement
                items:
                  type: string
  '/arrangements/{arrangement}':
    get:
      tags:
        - Arrangements
      parameters:
        - name: arrangement
          in: path
          required: true
          example: 1_main-arrangement
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: Main
                  metadata:
                    type: object
                    properties:
                      defined:
                        type: boolean
                        description: |
                          Indicates if corresponding arrangement.yaml is present
                          (if not, arrangement is generated instead)
                      invalid:
                        type: boolean
                        default: false
                        description: >
                          Indicates that the corresponding arrangement.yaml is
                          invalid

                          (arrangement is generated instead)
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          example: bunny.mp4
                        type:
                          type: string
                          enum:
                            - image
                            - video
                          example: video
                        duration:
                          type: number
                          example: 23.57
                          description: >-
                            How long should the content be played (also for
                            images)
        '404':
          description: Not found
  '/arrangements/{arrangement}/{file}':
    get:
      tags:
        - Arrangements
      parameters:
        - name: arrangement
          in: path
          required: true
          example: 1_main-arrangement
          schema:
            type: string
        - name: file
          in: path
          required: true
          example: myVideo.mp4
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            video/mp4:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Not found
  /borrel-menu/:
    get:
      tags:
        - Borrel Menu
      responses:
        '200':
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
